### ISSUE TITLE
Glue Sticky button to the right

### ISSUE THREAD

**Issue by Only1rhaine** [ach-ref/StickyButton#1]
Hello can you please explain how to glue the button to the right? I can't seem to get it to stay there.

Thank you in advance!

**Comment by ach-ref** [comment]
Hi, what do you mean by glue it to the right ?

Like when the app restarts ?
If yes you can store the side in the UserDefaults and retrieve it at the app launching to update the button's side programmatically. That's what I do for my app using this pod.

```swift
let isOnRightSide = UserDefaults.standard.bool(forKey: K.User.MENU_BUTTON_RIGHT_SIDE)
let side: StickyButtonSide = isOnRightSide ? .right : .left
menuButton.setStickySide(side)
```

Otherwise please give me more details.

**Comment by Only1rhaine** [comment]
Hello,

Yes that is what I meant.

Thank you so much for you help!

**Comment by ach-ref** [comment]
Pleasure :)

**Comment by Only1rhaine** [comment]
Hi 👋🏾,

It’s me again so my developer can’t get the button to stick to the right side and I sent him screen shots of your response. What could possibly be the issue?

Thanks!

Jacqueline

**Comment by ach-ref** [comment]
Hi,

A possible reason would be that he’s trying to stick it to the right too soon in the button’s life cycle. He probably should do it in the viewDidLoad of the button’s viewController.

I hope it will help :)

On 15 May 2020, at 00:55, Only1rhaine <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi 👋🏾,

It’s me again so my developer can’t get the button to stick to the right side and I sent him screen shots of your response. What could possibly be the issue?

Thanks!

Jacqueline

**Comment by Only1rhaine** [comment]
Thank you!

Jacqueline

**Comment by ach-ref** [comment]
No worries at all. Feel free to give it a star on GitHub if you like the pod :)

Regards,

On 16 May 2020, at 17:07, Only1rhaine <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you!

Jacqueline

**Comment by Only1rhaine** [comment]
Will do!
